### ISSUE TITLE
Proposer mongo-express pour visualiser le contenu de la base Mongo

### ISSUE THREAD

**Issue by gbrunois** [Sfeir/sfeir-school-nodejs#37]
⚠️  Attention, ça n'a rien à voir avec ExpressJS

```
version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: schoolsdb
    networks:
      - api
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - api   
networks:
  api:
```
